// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: playground-grpc.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TodoData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body  string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *TodoData) Reset() {
	*x = TodoData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoData) ProtoMessage() {}

func (x *TodoData) ProtoReflect() protoreflect.Message {
	mi := &file_playground_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoData.ProtoReflect.Descriptor instead.
func (*TodoData) Descriptor() ([]byte, []int) {
	return file_playground_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *TodoData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TodoData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TodoData) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_playground_grpc_proto protoreflect.FileDescriptor

var file_playground_grpc_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2d, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0xa6, 0x01,
	0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x47, 0x72, 0x70, 0x63,
	0x12, 0x24, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x09,
	0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x09, 0x2e, 0x54, 0x6f, 0x64, 0x6f,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f,
	0x64, 0x6f, 0x12, 0x09, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x09, 0x2e,
	0x54, 0x6f, 0x64, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x24, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x09, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x09, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00,
	0x12, 0x24, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x09,
	0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x09, 0x2e, 0x54, 0x6f, 0x64, 0x6f,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x2d, 0x6a, 0x75, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_playground_grpc_proto_rawDescOnce sync.Once
	file_playground_grpc_proto_rawDescData = file_playground_grpc_proto_rawDesc
)

func file_playground_grpc_proto_rawDescGZIP() []byte {
	file_playground_grpc_proto_rawDescOnce.Do(func() {
		file_playground_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_playground_grpc_proto_rawDescData)
	})
	return file_playground_grpc_proto_rawDescData
}

var file_playground_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_playground_grpc_proto_goTypes = []interface{}{
	(*TodoData)(nil), // 0: TodoData
}
var file_playground_grpc_proto_depIdxs = []int32{
	0, // 0: PlaygroundGrpc.CreateTodo:input_type -> TodoData
	0, // 1: PlaygroundGrpc.ReadTodo:input_type -> TodoData
	0, // 2: PlaygroundGrpc.UpdateTodo:input_type -> TodoData
	0, // 3: PlaygroundGrpc.DeleteTodo:input_type -> TodoData
	0, // 4: PlaygroundGrpc.CreateTodo:output_type -> TodoData
	0, // 5: PlaygroundGrpc.ReadTodo:output_type -> TodoData
	0, // 6: PlaygroundGrpc.UpdateTodo:output_type -> TodoData
	0, // 7: PlaygroundGrpc.DeleteTodo:output_type -> TodoData
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_playground_grpc_proto_init() }
func file_playground_grpc_proto_init() {
	if File_playground_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_playground_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_playground_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_playground_grpc_proto_goTypes,
		DependencyIndexes: file_playground_grpc_proto_depIdxs,
		MessageInfos:      file_playground_grpc_proto_msgTypes,
	}.Build()
	File_playground_grpc_proto = out.File
	file_playground_grpc_proto_rawDesc = nil
	file_playground_grpc_proto_goTypes = nil
	file_playground_grpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlaygroundGrpcClient is the client API for PlaygroundGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaygroundGrpcClient interface {
	CreateTodo(ctx context.Context, in *TodoData, opts ...grpc.CallOption) (*TodoData, error)
	ReadTodo(ctx context.Context, in *TodoData, opts ...grpc.CallOption) (*TodoData, error)
	UpdateTodo(ctx context.Context, in *TodoData, opts ...grpc.CallOption) (*TodoData, error)
	DeleteTodo(ctx context.Context, in *TodoData, opts ...grpc.CallOption) (*TodoData, error)
}

type playgroundGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaygroundGrpcClient(cc grpc.ClientConnInterface) PlaygroundGrpcClient {
	return &playgroundGrpcClient{cc}
}

func (c *playgroundGrpcClient) CreateTodo(ctx context.Context, in *TodoData, opts ...grpc.CallOption) (*TodoData, error) {
	out := new(TodoData)
	err := c.cc.Invoke(ctx, "/PlaygroundGrpc/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playgroundGrpcClient) ReadTodo(ctx context.Context, in *TodoData, opts ...grpc.CallOption) (*TodoData, error) {
	out := new(TodoData)
	err := c.cc.Invoke(ctx, "/PlaygroundGrpc/ReadTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playgroundGrpcClient) UpdateTodo(ctx context.Context, in *TodoData, opts ...grpc.CallOption) (*TodoData, error) {
	out := new(TodoData)
	err := c.cc.Invoke(ctx, "/PlaygroundGrpc/UpdateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playgroundGrpcClient) DeleteTodo(ctx context.Context, in *TodoData, opts ...grpc.CallOption) (*TodoData, error) {
	out := new(TodoData)
	err := c.cc.Invoke(ctx, "/PlaygroundGrpc/DeleteTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaygroundGrpcServer is the server API for PlaygroundGrpc service.
type PlaygroundGrpcServer interface {
	CreateTodo(context.Context, *TodoData) (*TodoData, error)
	ReadTodo(context.Context, *TodoData) (*TodoData, error)
	UpdateTodo(context.Context, *TodoData) (*TodoData, error)
	DeleteTodo(context.Context, *TodoData) (*TodoData, error)
}

// UnimplementedPlaygroundGrpcServer can be embedded to have forward compatible implementations.
type UnimplementedPlaygroundGrpcServer struct {
}

func (*UnimplementedPlaygroundGrpcServer) CreateTodo(context.Context, *TodoData) (*TodoData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTodo not implemented")
}
func (*UnimplementedPlaygroundGrpcServer) ReadTodo(context.Context, *TodoData) (*TodoData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTodo not implemented")
}
func (*UnimplementedPlaygroundGrpcServer) UpdateTodo(context.Context, *TodoData) (*TodoData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTodo not implemented")
}
func (*UnimplementedPlaygroundGrpcServer) DeleteTodo(context.Context, *TodoData) (*TodoData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTodo not implemented")
}

func RegisterPlaygroundGrpcServer(s *grpc.Server, srv PlaygroundGrpcServer) {
	s.RegisterService(&_PlaygroundGrpc_serviceDesc, srv)
}

func _PlaygroundGrpc_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundGrpcServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PlaygroundGrpc/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundGrpcServer).CreateTodo(ctx, req.(*TodoData))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaygroundGrpc_ReadTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundGrpcServer).ReadTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PlaygroundGrpc/ReadTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundGrpcServer).ReadTodo(ctx, req.(*TodoData))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaygroundGrpc_UpdateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundGrpcServer).UpdateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PlaygroundGrpc/UpdateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundGrpcServer).UpdateTodo(ctx, req.(*TodoData))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaygroundGrpc_DeleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundGrpcServer).DeleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PlaygroundGrpc/DeleteTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundGrpcServer).DeleteTodo(ctx, req.(*TodoData))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlaygroundGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PlaygroundGrpc",
	HandlerType: (*PlaygroundGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _PlaygroundGrpc_CreateTodo_Handler,
		},
		{
			MethodName: "ReadTodo",
			Handler:    _PlaygroundGrpc_ReadTodo_Handler,
		},
		{
			MethodName: "UpdateTodo",
			Handler:    _PlaygroundGrpc_UpdateTodo_Handler,
		},
		{
			MethodName: "DeleteTodo",
			Handler:    _PlaygroundGrpc_DeleteTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playground-grpc.proto",
}
